### ISSUE TITLE
Documentation via pkg.go.dev not available; requires license file in repo

### ISSUE THREAD

**Issue by mewmew** [coding-socks/matroska#5]
Hi László!

Thanks a lot for working on the matroska package and sharing it with the broader open source community. It looks like a very faithful implementation with references to the spec.

I tried to get an overview of the API of the matroska package using pkg.go.dev. However, pkg.go.dev seems to be unable to locate a license file in the matroska repository, and thus fail to provide access to the documentation.

https://pkg.go.dev/github.com/coding-socks/matroska

![screenshot_2022-11-09_19:16:44](https://user-images.githubusercontent.com/1414531/200909821-85f12d8b-268d-4aed-8a56-e07fca37f428.png)

Please consider adding a LICENSE file to the repository.

Wish you a lovely winter time ahead.

Cheerful regards,
Robin

**Comment by nerg4l** [comment]
Sorry, that's a mistake from my side. I forgot to add a license file when I moved github.com/coding-socks/matroska out from github.com/coding-socks/ebml.

**Comment by mewmew** [comment]
@nerg4l, you've got an incredible response time! : )

**Comment by mewmew** [comment]
P.S. are you on Discord by chance? I have a few API questions, but they may be better suited for chat than GitHub issues.

Cheers,
Robin

**Comment by nerg4l** [comment]
@mewmew You can find me on Discord as `System#7985`.
